# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieFun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieFun

  pod 'Alamofire'
  
  pod 'SwiftyJSON'
  
  pod 'Firebase/Core'
  
  pod 'Firebase/Auth'
  
  pod 'Firebase/Firestore'
  
  pod 'Firebase/Storage'
  
  pod 'SDWebImage'
  
  pod 'SVProgressHUD', '~> 2.2'

  pod 'YoutubePlayer-in-WKWebView', '~> 0.3'
  
  pod 'RealmSwift'
  
end
